export const REG_USERS = [
  {
    id: 0,
    name: "Guest",
    password: "Guest",
    role: "user",
  },
  {
    id: 1,
    name: "favour",
    password: "132546Fa",
    role: "admin",
    position: "user",
  },
  {
    id: 2,
    name: "jindu",
    password: "132546Jd",
    role: "admin",
    position: "Asst.Sec",
  },
  {
    id: 3,
    name: "Emmanuel",
    password: "132546Em",
    role: "admin",
    position: "Chairman",
  },
  {
    id: 4,
    name: "Victor",
    password: "132546Vi",
    role: "admin",
    position: "User",
  },
  {
    id: 5,
    name: "Obiorah",
    password: "132546Ob",
    role: "User",
    position: "User",
  },
  {
    id: 6,
    name: "Jahswill",
    password: "132546Jw",
    role: "User",
    position: "User",
  },
  {
    id: 7,
    name: "Cynthia",
    password: "132546Cy",
    role: "User",
    position: "User",
  },
  {
    id: 8,
    name: "Chukwuekwu",
    password: "132546Ck",
    role: "User",
    position: "User",
  },
  {
    id: 8,
    name: "Ojieh",
    password: "132546Oj",
    role: "User",
    position: "User",
  },
  {
    id: 9,
    name: "Simeon",
    password: "132546Sm",
    role: "User",
    position: "User",
  },
  {
    id: 10,
    name: "Chidi",
    password: "132546Ch",
    role: "User",
    position: "User",
  },
];
